### ISSUE TITLE
Will not import with with python 3.5

### ISSUE THREAD

**Issue by oppsig** [ZhukovAlexander/triegex#6]
```
import triegex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/share/virtualenvs/project-xy-SPS3Z/lib/python3.5/site-packages/triegex/__init__.py", line 29
    return f'<TriegexNode: \'{self.char}\' end={self.end}>'
```

**Comment by ZhukovAlexander** [comment]
Hi @oppsig ! Which version of the package do you use? This issue was fixed in #3 .
